# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7f0dc20a736ccc942a0e3e533641f317509b4388e3b36b4877ed72af085e2e7f2cfe5981f4d52eb6868cfdb0aa54c36f33096d3bd7858670ce9230a8a3e8455

test:
  secret_key_base: d06719a00480179ce15b32439eb8129df87f0100d26e0b041b73a731b92f06f3a73e83a51b5d881f51f27ab568123386c58aa82d0eb36900960dcffd79fc667d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
